import type { LucideIcon } from "lucide-react";
import {
  Bird,
  BookOpen,
  Bot,
  Brain,
  Bug,
  Calculator,
  Camera,
  Cat,
  Cloud,
  Code,
  Coffee,
  Compass,
  Cpu,
  Crown,
  Database,
  Droplets,
  Feather,
  Fingerprint,
  Fish,
  Flame,
  FlaskConical,
  Flower2,
  Ghost,
  GitBranch,
  Globe,
  Hammer,
  Heart,
  Hexagon,
  Home,
  Inbox,
  Key,
  Landmark,
  Leaf,
  Lightbulb,
  Lock,
  Mail,
  Map,
  MessageSquare,
  MessagesSquare,
  Mic,
  Moon,
  Mountain,
  Music,
  Orbit,
  Palette,
  PawPrint,
  PenLine,
  Puzzle,
  Rabbit,
  Radar,
  Rocket,
  Search,
  Shield,
  Ship,
  Sparkles,
  Sprout,
  Star,
  Sun,
  Target,
  Telescope,
  Terminal,
  Trees,
  WandSparkles,
  Wrench,
  Zap,
} from "lucide-react";

/**
 * Curated lucide-react icons for agent identity. Keys are the lucide
 * export names the API stores on `Agent.icon` (default "Bot").
 */
export const AGENT_ICONS = {
  Bird,
  BookOpen,
  Bot,
  Brain,
  Bug,
  Calculator,
  Camera,
  Cat,
  Cloud,
  Code,
  Coffee,
  Compass,
  Cpu,
  Crown,
  Database,
  Droplets,
  Feather,
  Fingerprint,
  Fish,
  Flame,
  FlaskConical,
  Flower2,
  Ghost,
  GitBranch,
  Globe,
  Hammer,
  Heart,
  Hexagon,
  Home,
  Inbox,
  Key,
  Landmark,
  Leaf,
  Lightbulb,
  Lock,
  Mail,
  Map,
  MessageSquare,
  MessagesSquare,
  Mic,
  Moon,
  Mountain,
  Music,
  Orbit,
  Palette,
  PawPrint,
  PenLine,
  Puzzle,
  Rabbit,
  Radar,
  Rocket,
  Search,
  Shield,
  Ship,
  Sparkles,
  Sprout,
  Star,
  Sun,
  Target,
  Telescope,
  Terminal,
  Trees,
  WandSparkles,
  Wrench,
  Zap,
} as const satisfies Record<string, LucideIcon>;

export type AgentIconName = keyof typeof AGENT_ICONS;

export const AGENT_ICON_NAMES = Object.keys(AGENT_ICONS) as AgentIconName[];

export const DEFAULT_AGENT_ICON: AgentIconName = "Bot";

export const AGENT_ICON_KEYWORDS: Record<AgentIconName, string[]> = {
  Bird: ["animal", "fly"],
  BookOpen: ["read", "docs"],
  Bot: ["robot", "agent", "assistant"],
  Brain: ["think", "mind", "reason"],
  Bug: ["insect", "debug"],
  Calculator: ["math", "numbers"],
  Camera: ["photo", "image"],
  Cat: ["animal"],
  Cloud: ["weather", "sky"],
  Code: ["developer", "program", "builder"],
  Coffee: ["cafe", "break"],
  Compass: ["navigate", "direction"],
  Cpu: ["chip", "compute"],
  Crown: ["lead", "king"],
  Database: ["sql", "data", "postgres"],
  Droplets: ["water", "rain"],
  Feather: ["write", "light"],
  Fingerprint: ["identity", "unique"],
  Fish: ["animal", "water"],
  Flame: ["fire", "hot"],
  FlaskConical: ["lab", "science", "test"],
  Flower2: ["bloom", "plant"],
  Ghost: ["spirit", "fun"],
  GitBranch: ["git", "vcs"],
  Globe: ["web", "world", "internet"],
  Hammer: ["build", "tool"],
  Heart: ["love", "care"],
  Hexagon: ["shape", "hive"],
  Home: ["house", "base"],
  Inbox: ["mail", "a2a"],
  Key: ["secret", "access"],
  Landmark: ["place", "civic"],
  Leaf: ["plant", "green"],
  Lightbulb: ["idea", "think"],
  Lock: ["secure", "private"],
  Mail: ["email", "inbox"],
  Map: ["navigate", "place"],
  MessageSquare: ["chat", "talk"],
  MessagesSquare: ["chat", "thread"],
  Mic: ["voice", "audio"],
  Moon: ["night", "dark"],
  Mountain: ["peak", "earth"],
  Music: ["audio", "sound"],
  Orbit: ["space", "cycle"],
  Palette: ["art", "color", "design"],
  PawPrint: ["animal", "pet"],
  PenLine: ["write", "edit"],
  Puzzle: ["piece", "solve"],
  Rabbit: ["animal", "hare"],
  Radar: ["scan", "detect"],
  Rocket: ["launch", "ship"],
  Search: ["find", "lookup", "scout"],
  Shield: ["secure", "protect"],
  Ship: ["boat", "sail"],
  Sparkles: ["magic", "ai", "stars"],
  Sprout: ["plant", "grow", "garden"],
  Star: ["favorite", "highlight"],
  Sun: ["day", "light"],
  Target: ["goal", "aim"],
  Telescope: ["look", "space"],
  Terminal: ["shell", "cli", "console"],
  Trees: ["forest", "plant"],
  WandSparkles: ["magic", "wand"],
  Wrench: ["tool", "fix"],
  Zap: ["bolt", "fast", "energy"],
};

export function isAgentIconName(value: unknown): value is AgentIconName {
  return typeof value === "string" && value in AGENT_ICONS;
}

export function resolveAgentIconName(value: unknown): AgentIconName {
  return isAgentIconName(value) ? value : DEFAULT_AGENT_ICON;
}

export function resolveAgentIcon(value: unknown): AgentIconName {
  return resolveAgentIconName(value);
}

export function getAgentIcon(value: unknown): LucideIcon {
  return AGENT_ICONS[resolveAgentIconName(value)];
}

export function searchAgentIcons(query: string): AgentIconName[] {
  const needle = query.trim().toLowerCase();
  if (!needle) return AGENT_ICON_NAMES;
  return AGENT_ICON_NAMES.filter((name) => {
    if (name.toLowerCase().includes(needle)) return true;
    return (AGENT_ICON_KEYWORDS[name] ?? []).some((keyword) => keyword.includes(needle));
  });
}
